version: '3.8'
services:
  frontend:
    build: ./react-mui-csv-app
    ports:
      - "3000:80"
    depends_on:
      - backend
  backend:
    env_file:
         - .env
    build: ./backend
    ports:
      - "5001:5000" 