version: '3.8'

services:
  frontend:
    build: ./react-mui-csv-app
    container_name: daxco-frontend
    restart: unless-stopped
    ports:
      - '3000:80'
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - daxco-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  backend:
    build: ./backend
    container_name: daxco-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - '5001:5000'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - daxco-network
    volumes:
      - ./backend/logs:/app/logs

networks:
  daxco-network:
    driver: bridge